backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    file: "projects.json"
    fields:
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Meta", name: "meta", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
    
  - name: "writings"
    label: "Writings"
    file: "writings.json"
    fields:
      - label: "Writings"
        name: "writings"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta", name: "meta", widget: "string" }
          - { label: "Excerpt", name: "excerpt", widget: "text" }
    
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "about.json"
        fields:
          - label: "Paragraphs"
            name: "paragraphs"
            widget: "list"
            field:
              label: "Paragraph"
              name: "paragraph"
              widget: "text"
